### ISSUE TITLE
Mod Manager todo

### ISSUE THREAD

**Issue by ElPumpo** [Council-of-the-Delverers/Delver-Unlimited#1]
- [x] compatibility with all mods by creating `mod.json` if it doesn't exist
    - [x] reach out moddes to support the D-U mod format @Drakensin 
- [x] add proper footer to `ModManagerScreen`
     - [x]  a `BACK` button
- [x] notify user to restart when disabing / enabling mod
- [x] failsafes for e.g if the `/mods` folder doesn't exist, etc
- [x] hide WWW button if `url` is empty
